use_frameworks!

platform :ios, '11.0'

target 'ZLUIUtilities_Example' do
  pod 'ZLUIUtilities', :path => '../'


  pod 'ZLBaseUI', :git => 'https://github.com/ExistOrLive/ZLBaseUI.git', :tag => '1.2.1'
  #pod 'ZLBaseUI', :path => "../../ZLBaseUI"

  pod 'ZLBaseExtension', :git => "https://github.com/ExistOrLive/ZLBaseExtension.git", :tag => '1.2.0'


  target 'ZLUIUtilities_Tests' do
    inherit! :search_paths

    
  end
end
